<a href="https://colab.research.google.com/github/syafaatunisa/DAA/blob/main/DAA_(14_09_22)_pt3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
alist = ["syafa", 2021, "UPJ", True]
print("alist = ", alist)

alist =  ['syafa', 2021, 'UPJ', True]


Latihan

In [5]:
Mahasiswa = ["Syafaatunisa", 2021071014, "Informatika", "DAA", "14/09/2022" , "Universitas pembangunan jaya"]
print("Mahasiswa = ", Mahasiswa)

Mahasiswa =  ['Syafaatunisa', 2021071014, 'Informatika', 'DAA', '14/09/2022', 'Universitas pembangunan jaya']


Latihan 2


In [6]:
bin_colors = ["Red", "Green", "Blue", "Yellow"]
bin_colors[1]

'Green'

In [7]:
#mengambil lebih dari 1 index
bin_colors[0:4]

['Red', 'Green', 'Blue', 'Yellow']

Latihan 3

In [8]:
Mahasiswa = ["Syafaatunisa", 2021071014, "Informatika", "DAA", "14/09/2022" , "Universitas pembangunan jaya"]
Mahasiswa [1]

2021071014

In [9]:
Mahasiswa[0]

'Syafaatunisa'

In [10]:
Mahasiswa[5]

'Universitas pembangunan jaya'

In [11]:
Mahasiswa [1:3]

[2021071014, 'Informatika']

In [12]:
bin_colors = ["Red", "Green", "Blue", "Yellow"]
for aColor in bin_colors:
  print(aColor + "square")

Redsquare
Greensquare
Bluesquare
Yellowsquare


cetak isi list "mahasiswa" tambahkan kata "UPJ" di depan!!

In [13]:
for cetak in Mahasiswa:
  print("UPJ", cetak)

UPJ Syafaatunisa
UPJ 2021071014
UPJ Informatika
UPJ DAA
UPJ 14/09/2022
UPJ Universitas pembangunan jaya


Striktur data tuples

In [14]:
bin_colors = ("Red", "Green", "Blue", "Yellow")
bin_colors[1]
bin_colors[2:]

('Blue', 'Yellow')

Susun tumple bernama "upj" isi dengan universitas, pembangunan, jaya

In [15]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
print(UPJ)
UPJ[:3]

('Universitas', 'Pembangunan', 'Jaya')


('Universitas', 'Pembangunan', 'Jaya')

Latihan
Buat tuple bersarang bernama "nested_tuple dengan nilai
pertama = 100
kedua = 200,400,600
ketiga = 300
keempat = 400,800

In [16]:
Nested_tuple = ((100), (200,400,600), (300), (400,800))
print("pertama", Nested_tuple[0])
print("kedua", Nested_tuple[1])
print("ketiga", Nested_tuple[2])
print("keempat", Nested_tuple[3])

pertama 100
kedua (200, 400, 600)
ketiga 300
keempat (400, 800)


Struktur Data dalam Python: Dictionary

In [17]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [22]:
bin_colors.get('approved_color')
bin_colors['approved_color']

'Green'

In [23]:
Data = {"Nama" : "Syafa'atunisa", "NIM" : "2021071014", "Prodi" : "Informatika", "Universitas" : "UPJ"}
print(Data)

{'Nama': "Syafa'atunisa", 'NIM': '2021071014', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


Struktur Data dalam Python:Sets


In [24]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [25]:
green = {'grass', 'leaves','leaves'}
print(green)

{'grass', 'leaves'}


In [26]:
red = {'dandelions', 'fire hydrant', 'blood', 'rose', 'leaves'}
yellow = {'fire hydrant', 'blood', 'rose', 'leaves'}

print(yellow|red)
print(yellow&red)

{'blood', 'fire hydrant', 'dandelions', 'leaves', 'rose'}
{'blood', 'fire hydrant', 'leaves', 'rose'}


In [27]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])

print(df)



   0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True


In [28]:
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [29]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [30]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [31]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [32]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [33]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

Buat dataframe bernama mhs, dengan data berikut:


In [37]:
 df = pd.DataFrame([['1', 'Informatika', 50, 30, 20], 
                   ['2', 'Sistem Informasi', 55, 30, 25], 
                   ['3', 'Teknik Sipil', 40, 30, 10]])


In [38]:
df.columns = ['no', 'Prodi', 'Mahasiswa', 'Lakilaki', 'Perempuan']
df

no             Prodi  Mahasiswa  Lakilaki  Perempuan
0  1       Informatika         50        30         20
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10

In [40]:
import numpy as np

In [41]:
myMatrix = np.array([
                    [11, 12, 13], 
                    [21, 22, 23],
                    [31, 32, 33]])
print (myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [42]:
print (type(myMatrix))

<class 'numpy.ndarray'>


In [43]:
myMatrix2 = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800],
])
print (f'Original Array:\n{myMatrix2}')
myMatrix2_transposed = myMatrix2.transpose()
print (f'Transposed Array:\n{myMatrix2_transposed}')

Original Array:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Transposed Array:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [44]:
myVector = [22, 33, 44, 55]
print (myVector)
print (type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [45]:
myVector = np.array ([22, 33, 44, 55])
print (myVector)
print (type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [46]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-I]
  def size(self):
    return len(self.items)

In [47]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

print(stack.pop())

print(stack.isEmpty())

Yellow
False


In [48]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [49]:
queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [50]:
print(queue.dequeue())
print(queue.dequeue())

Red
Green
